"""add discussion destinataire

Revision ID: 3af8720c91df
Revises: d8ce1f8f601f
Create Date: 2026-07-22 00:39:14.414556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af8720c91df'
down_revision: Union[str, Sequence[str], None] = 'd8ce1f8f601f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('destinataire_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'discussions', 'utilisateurs', ['destinataire_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discussions', type_='foreignkey')
    op.drop_column('discussions', 'destinataire_id')
    # ### end Alembic commands ###
