"""add fcm tokens and notification reference_id

Revision ID: 47f3ee03bbf0
Revises: 3af8720c91df
Create Date: 2026-07-22 11:06:45.054101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f3ee03bbf0'
down_revision: Union[str, Sequence[str], None] = '3af8720c91df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False)
    op.add_column('notifications', sa.Column('reference_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate ne détecte pas les nouveaux membres d'un enum Postgres existant.
    op.execute("ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'RELANCE'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reference_id')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
