"""add updated_at to mandats

Revision ID: 4e5d53521450
Revises: 379708fdfae5
Create Date: 2026-07-21 12:10:45.438870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e5d53521450'
down_revision: Union[str, Sequence[str], None] = '379708fdfae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### (nullable=True pour ne pas
    # casser les lignes existantes, puis backfill + NOT NULL, adapté à la main)
    op.add_column('mandats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE mandats SET updated_at = now() WHERE updated_at IS NULL")
    op.alter_column('mandats', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mandats', 'updated_at')
    # ### end Alembic commands ###
