"""add permissions and manager_permissions

Revision ID: 64b8063d2060
Revises: e1d777b4bf83
Create Date: 2026-07-20 16:12:56.062674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b8063d2060'
down_revision: Union[str, Sequence[str], None] = 'e1d777b4bf83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Catalogue fixe des permissions qu'un propriétaire peut accorder à un gestionnaire.
PERMISSIONS = [
    ("VOIR", "Consulter", "Voir les biens, lots, baux, échéances, paiements et quittances du propriétaire"),
    ("CREER_BIEN", "Créer un bien", "Ajouter un nouveau bien pour le propriétaire"),
    ("MODIFIER_BIEN", "Modifier un bien", "Modifier un bien existant du propriétaire"),
    ("SUPPRIMER_BIEN", "Supprimer un bien", "Supprimer un bien du propriétaire"),
    ("CREER_LOT", "Créer un lot", "Ajouter un lot à un bien du propriétaire"),
    ("MODIFIER_LOT", "Modifier un lot", "Modifier un lot existant"),
    ("SUPPRIMER_LOT", "Supprimer un lot", "Supprimer un lot"),
    ("CREER_BAIL", "Créer un bail", "Créer un contrat de location"),
    ("MODIFIER_BAIL", "Modifier un bail", "Modifier un contrat de location existant"),
    ("SUPPRIMER_BAIL", "Supprimer un bail", "Supprimer un contrat de location"),
    ("CREER_ECHEANCE", "Créer une échéance", "Ajouter manuellement une échéance à un bail"),
    ("MODIFIER_ECHEANCE", "Modifier une échéance", "Modifier une échéance existante"),
    ("CREER_PAIEMENT", "Enregistrer un paiement", "Enregistrer un paiement sur une échéance"),
    ("MODIFIER_PAIEMENT", "Modifier un paiement", "Modifier un paiement existant"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('manager_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandat_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('date_attribution', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mandat_id'], ['mandats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandat_id', 'permission_id', name='uq_manager_permission')
    )
    op.create_index(op.f('ix_manager_permissions_id'), 'manager_permissions', ['id'], unique=False)
    # ### end Alembic commands ###

    permissions_table = sa.table(
        "permissions",
        sa.column("code", sa.String),
        sa.column("libelle", sa.String),
        sa.column("description", sa.Text),
    )
    op.bulk_insert(
        permissions_table,
        [{"code": code, "libelle": libelle, "description": description} for code, libelle, description in PERMISSIONS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_permissions_id'), table_name='manager_permissions')
    op.drop_table('manager_permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
