"""add usage limits to subscription_plans

Revision ID: 67ac71d1356d
Revises: 4e5d53521450
Create Date: 2026-07-21 16:35:56.844193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ac71d1356d'
down_revision: Union[str, Sequence[str], None] = '4e5d53521450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### (server_default
    # ajouté à la main pour backfiller les plans existants avec -1 = illimité)
    op.add_column('subscription_plans', sa.Column('max_biens', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('max_lots', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('max_baux_actifs', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('max_gestionnaires', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('max_locataires', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('max_quittances_mois', sa.Integer(), nullable=False, server_default='-1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'max_quittances_mois')
    op.drop_column('subscription_plans', 'max_locataires')
    op.drop_column('subscription_plans', 'max_gestionnaires')
    op.drop_column('subscription_plans', 'max_baux_actifs')
    op.drop_column('subscription_plans', 'max_lots')
    op.drop_column('subscription_plans', 'max_biens')
    # ### end Alembic commands ###
