"""add encaisse_par to paiements

Revision ID: 7a9e4530a003
Revises: 31a4fb31f09b
Create Date: 2026-07-21 15:36:47.946927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9e4530a003'
down_revision: Union[str, Sequence[str], None] = '31a4fb31f09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('encaisse_par', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paiements', 'utilisateurs', ['encaisse_par'], ['id'])
    # ### end Alembic commands ###

    # Backfill existing rows before enforcing NOT NULL, otherwise this migration
    # breaks on any database that already has paiements (auto-generated by Alembic
    # assumed an empty table).
    op.execute(
        """
        UPDATE paiements
        SET encaisse_par = (
            SELECT id FROM utilisateurs
            ORDER BY (role = 'ADMINISTRATEUR') DESC, id
            LIMIT 1
        )
        WHERE encaisse_par IS NULL
        """
    )
    op.alter_column('paiements', 'encaisse_par', existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paiements', type_='foreignkey')
    op.drop_column('paiements', 'encaisse_par')
    # ### end Alembic commands ###
