"""add reclamations table

Revision ID: 95dcb3f0e596
Revises: 47f3ee03bbf0
Create Date: 2026-07-22 15:39:11.125185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dcb3f0e596'
down_revision: Union[str, Sequence[str], None] = '47f3ee03bbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclamations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proprietaire_id', sa.Integer(), nullable=False),
    sa.Column('sujet', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'REJETEE', name='reclamation_status'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('traite_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['traite_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclamations_id'), 'reclamations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reclamations_id'), table_name='reclamations')
    op.drop_table('reclamations')
    # ### end Alembic commands ###
