"""add receiver to discussions

Revision ID: a627dfd0fa51
Revises: 727c118de9bf
Create Date: 2026-07-22 15:58:01.929694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a627dfd0fa51'
down_revision: Union[str, Sequence[str], None] = '727c118de9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'discussions', 'utilisateurs', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discussions', type_='foreignkey')
    op.drop_column('discussions', 'receiver_id')
    # ### end Alembic commands ###
