"""Add target_role to subscription_plan

Revision ID: a652f15f38a3
Revises: c1ffb754e5ce
Create Date: 2026-08-24 12:31:42.487742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a652f15f38a3'
down_revision: Union[str, Sequence[str], None] = 'c1ffb754e5ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agence_membres_agence_id'), table_name='agence_membres')
    op.drop_index(op.f('ix_agence_membres_utilisateur_id'), table_name='agence_membres')
    op.drop_index(op.f('uq_agence_membres_active_utilisateur'), table_name='agence_membres', postgresql_where="(statut = 'ACTIF'::agence_membre_status)")
    op.drop_index(op.f('ix_charges_bien_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_lot_id'), table_name='charges')
    op.drop_index(op.f('ix_demandes_maintenance_bail_id'), table_name='demandes_maintenance')
    op.drop_index(op.f('ix_demandes_maintenance_locataire_id'), table_name='demandes_maintenance')
    op.drop_index(op.f('uq_invitations_client_pending'), table_name='invitations_client', postgresql_where="(statut = 'EN_ATTENTE'::invitation_client_status)")
    op.add_column('subscription_plans', sa.Column('target_role', sa.Enum('ADMINISTRATEUR', 'PROPRIETAIRE', 'GESTIONNAIRE', 'LOCATAIRE', name='utilisateur_role'), server_default='PROPRIETAIRE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'target_role')
    op.create_index(op.f('uq_invitations_client_pending'), 'invitations_client', ['agence_id', 'proprietaire_id'], unique=True, postgresql_where="(statut = 'EN_ATTENTE'::invitation_client_status)")
    op.create_index(op.f('ix_demandes_maintenance_locataire_id'), 'demandes_maintenance', ['locataire_id'], unique=False)
    op.create_index(op.f('ix_demandes_maintenance_bail_id'), 'demandes_maintenance', ['bail_id'], unique=False)
    op.create_index(op.f('ix_charges_lot_id'), 'charges', ['lot_id'], unique=False)
    op.create_index(op.f('ix_charges_bien_id'), 'charges', ['bien_id'], unique=False)
    op.create_index(op.f('uq_agence_membres_active_utilisateur'), 'agence_membres', ['utilisateur_id'], unique=True, postgresql_where="(statut = 'ACTIF'::agence_membre_status)")
    op.create_index(op.f('ix_agence_membres_utilisateur_id'), 'agence_membres', ['utilisateur_id'], unique=False)
    op.create_index(op.f('ix_agence_membres_agence_id'), 'agence_membres', ['agence_id'], unique=False)
    # ### end Alembic commands ###
