"""refactor_subscriptions_target_and_agence

Revision ID: b5d159a100ec
Revises: a652f15f38a3
Create Date: 2026-08-24 12:53:19.902540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
# revision identifiers, used by Alembic.
revision: str = 'b5d159a100ec'
down_revision: Union[str, Sequence[str], None] = 'a652f15f38a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new enum type first
    subscription_target_enum = postgresql.ENUM('PROPRIETAIRE', 'AGENCE', name='subscription_target_enum')
    subscription_target_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('subscription_plans', sa.Column('target_type', sa.Enum('PROPRIETAIRE', 'AGENCE', name='subscription_target_enum'), nullable=False, server_default='PROPRIETAIRE'))
    
    # Migrate data from target_role if it exists
    op.execute("UPDATE subscription_plans SET target_type = 'AGENCE' WHERE target_role = 'GESTIONNAIRE'")
    
    op.add_column('subscription_plans', sa.Column('max_membres_agence', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('max_storage_mb', sa.Integer(), nullable=False, server_default='-1'))
    op.add_column('subscription_plans', sa.Column('can_export', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_column('subscription_plans', 'target_role')
    
    op.add_column('subscriptions', sa.Column('agence_id', sa.Integer(), nullable=True))
    op.alter_column('subscriptions', 'owner_id', existing_type=sa.INTEGER(), nullable=True)
    op.create_unique_constraint(None, 'subscriptions', ['agence_id'])
    op.create_foreign_key(None, 'subscriptions', 'agences', ['agence_id'], ['id'])
    
    # Add check constraint
    op.create_check_constraint('chk_subscription_owner_or_agence', 'subscriptions', 'owner_id IS NOT NULL OR agence_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('subscriptions', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscriptions', 'agence_id')
    op.add_column('subscription_plans', sa.Column('target_role', postgresql.ENUM('PROPRIETAIRE', 'GESTIONNAIRE', 'LOCATAIRE', 'ADMINISTRATEUR', name='utilisateur_role'), server_default=sa.text("'PROPRIETAIRE'::utilisateur_role"), autoincrement=False, nullable=False))
    op.drop_column('subscription_plans', 'can_export')
    op.drop_column('subscription_plans', 'max_storage_mb')
    op.drop_column('subscription_plans', 'max_membres_agence')
    op.drop_column('subscription_plans', 'target_type')
    # ### end Alembic commands ###
