"""add description column to biens and lots

Revision ID: d25168ed298b
Revises: afbcd0d8d1a4
Create Date: 2026-07-27 22:26:03.441187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25168ed298b'
down_revision: Union[str, Sequence[str], None] = 'afbcd0d8d1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biens', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('lots', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'description')
    op.drop_column('biens', 'description')
    # ### end Alembic commands ###
