"""add bien_photos table

Revision ID: d8ce1f8f601f
Revises: 67ac71d1356d
Create Date: 2026-07-21 23:32:17.468532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ce1f8f601f'
down_revision: Union[str, Sequence[str], None] = '67ac71d1356d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bien_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bien_id'], ['biens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bien_photos_id'), 'bien_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bien_photos_id'), table_name='bien_photos')
    op.drop_table('bien_photos')
    # ### end Alembic commands ###
