"""initial schema

Revision ID: e1d777b4bf83
Revises: 
Create Date: 2026-07-17 17:11:54.925267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d777b4bf83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('partenaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='partenaire_status'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partenaires_id'), 'partenaires', ['id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PROPRIETAIRE', 'GESTIONNAIRE', 'LOCATAIRE', 'ADMINISTRATEUR', name='utilisateur_role'), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('statut_compte', sa.Enum('ACTIF', 'INVITE_EN_ATTENTE', 'CREE_SANS_ACCES', name='statut_compte'), nullable=False),
    sa.Column('cree_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'PUBLIE', 'REJETE', name='avis_status'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avis_id'), 'avis', ['id'], unique=False)
    op.create_table('biens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proprietaire_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('statut', sa.Enum('DISPONIBLE', 'LOUE', 'MAINTENANCE', 'HORS_SERVICE', name='bien_status'), nullable=True),
    sa.Column('attachement', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biens_id'), 'biens', ['id'], unique=False)
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), nullable=False),
    sa.Column('pdf', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_id'), 'discussions', ['id'], unique=False)
    op.create_table('mandats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestionnaire_id', sa.Integer(), nullable=False),
    sa.Column('proprietaire_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'REVOQUE', name='mandat_status'), nullable=True),
    sa.ForeignKeyConstraint(['gestionnaire_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandats_id'), 'mandats', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('NON_LUE', 'LUE', name='notification_status'), nullable=False),
    sa.Column('type', sa.Enum('PAIEMENT', 'ECHEANCE', 'BAIL', 'MANDAT', 'DISCUSSION', name='notification_type'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('profils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('piece_identite', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_index(op.f('ix_profils_id'), 'profils', ['id'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('loyer_reference', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('LIBRE', 'OCCUPE', 'RESERVE', name='lot_status'), nullable=True),
    sa.Column('attachement', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bien_id'], ['biens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_id'), 'lots', ['id'], unique=False)
    op.create_table('baux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('locataire_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('loyer', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('depot', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACTIF', 'RESILIE', 'EXPIRE', name='bail_status'), nullable=True),
    sa.ForeignKeyConstraint(['locataire_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baux_id'), 'baux', ['id'], unique=False)
    op.create_table('echeances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bail_id', sa.Integer(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('montant_du', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('statut', sa.Enum('PAYE', 'PARTIEL', 'IMPAYE', name='echeance_status'), nullable=True),
    sa.ForeignKeyConstraint(['bail_id'], ['baux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_echeances_id'), 'echeances', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('echeance_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('date_paiement', sa.DateTime(), nullable=False),
    sa.Column('mode_paiement', sa.Enum('ESPECES', 'VIREMENT', 'CHEQUE', 'CARTE', 'MOBILE_MONEY', name='mode_paiement'), nullable=True),
    sa.ForeignKeyConstraint(['echeance_id'], ['echeances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_table('quittances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paiement_id', sa.Integer(), nullable=False),
    sa.Column('fichier_pdf', sa.String(length=255), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paiement_id'], ['paiements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paiement_id')
    )
    op.create_index(op.f('ix_quittances_id'), 'quittances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quittances_id'), table_name='quittances')
    op.drop_table('quittances')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_echeances_id'), table_name='echeances')
    op.drop_table('echeances')
    op.drop_index(op.f('ix_baux_id'), table_name='baux')
    op.drop_table('baux')
    op.drop_index(op.f('ix_lots_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_profils_id'), table_name='profils')
    op.drop_table('profils')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mandats_id'), table_name='mandats')
    op.drop_table('mandats')
    op.drop_index(op.f('ix_discussions_id'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_biens_id'), table_name='biens')
    op.drop_table('biens')
    op.drop_index(op.f('ix_avis_id'), table_name='avis')
    op.drop_table('avis')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_partenaires_id'), table_name='partenaires')
    op.drop_table('partenaires')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
