"""add champs to avis

Revision ID: eff12d67df74
Revises: 7a9e4530a003
Create Date: 2026-07-21 18:49:56.609013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff12d67df74'
down_revision: Union[str, Sequence[str], None] = '7a9e4530a003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avis', sa.Column('nom', sa.String(length=100), nullable=False))
    op.add_column('avis', sa.Column('prenom', sa.String(length=100), nullable=False))
    op.add_column('avis', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('avis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('avis', 'deleted_at')
    op.drop_column('avis', 'prenom')
    op.drop_column('avis', 'nom')
    # ### end Alembic commands ###
